//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.Data.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int ID { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<System.DateTime> RentalDate { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Extras { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
